### ISSUE TITLE
the model and the predict score has not been  displayed  in the host fateboard for the homo_lr algorithm

### ISSUE THREAD

**Issue by ZhanqiLiu** [FederatedAI/FATE#1410]
![image](https://user-images.githubusercontent.com/13013299/83101713-8b1b5280-a0e5-11ea-82ff-f8998162c5e5.png)
![image](https://user-images.githubusercontent.com/13013299/83101744-98d0d800-a0e5-11ea-83bf-20bf9cabc218.png)
![image](https://user-images.githubusercontent.com/13013299/83101816-c61d8600-a0e5-11ea-9b3d-ff14988ffcf7.png)

**Comment by tanmc123** [comment]
@ZhanqiLiu Do you set Paillier encrypt method for homo_lr? If so, this is what they are expected to be. 

Since if you set the model as encrypted, that means you don't want host obtain the final model. Thus model will not be shown. What's more, if the predict score is provided, host can also infer the model. Thus, predict score will not be transferred back neither.

**Comment by ZhanqiLiu** [comment]
thank you , this issue has been solved according to your guidance
