### ISSUE TITLE
"Hetero Feature Binning" leaks extra information

### ISSUE THREAD

**Issue by vincehong** [FederatedAI/FATE#1430]
As described in https://github.com/FederatedAI/FATE/tree/master/federatedml/feature , to calculate WOE,   B party who has the data labels encrypt its labels with homomorphic encryption and then send them to A.  A then calculate the sum of each bin's label and send back. During this process, party A leaks extra information: the number of samples in each bin.

For example: A and B want to compute this function together:  

                    What is the WOE if 30>= age >= 20 ?

But if they use FATE, B will know **how many A's client are between 20~30 years old !** I don't think this is always acceptable for A.

**Comment by tanmc123** [comment]
@vincehong That is not true. Actually, party B cannot obtain the feature information and bin split points at all. What party B know is that number of some bins of some features. That means in your case, party B cannot know it is a feature means age and the split points are 20 and 30 neither. 

Hope that can make you more clear about it. Thank you.

**Comment by vincehong** [comment]
I know what you mean. What B can know is : 

                 how many A's client are with the same feature X

while B does not know what X means. 

Actually, given the distribution, and the numbers X_1, X_2, ...X_n, B could figure out these features by a high chance.

**Comment by tanmc123** [comment]
@vincehong I didn't get how to figure out these features through the number x_1, x_2...etc. Please note it is not the distribution of X, but number of each bins.  Take quantile binning as an example, the number is supposed to be almost same in each bean with the condition of which total amount is not a secret among the parties. Is there any material supporting that?

As for what you meantion so call a "leak", if this information cannot benefit the other party, it makes no sense to define it as a "leak". Doesn't it?

**Comment by vincehong** [comment]
@tanmc123  Think about categorical features.   Suppose A has a feature X with 3 possible values X_1, X_2, X_3,  then B could know the exact number of samples for each value of X.  If this could not be a leak, then people would doubt what could be called a leak.

**Comment by tanmc123** [comment]
> @tanmc123 Think about categorical features. Suppose A has a feature X with 3 possible values X_1, X_2, X_3, then B could know the exact number of samples for each value of X. If this could not be a leak, then people would doubt what could be called a leak.

First of all, Party B should have a chance to know it is a categorical feature which is not so obviously through the binning. Then, party B cannot obtain what the feature means even if they could know that. So I still cannot get how to use this information to benefit party B. 

I don't think it's fair to say an algorithm is not safe just because "if we could know something else, it is not safe". 

As an engineer, we should always make trade off between it is completely safe and great usablity. Calculating WOE is very meaningful in practice but the risk is low enough. If you can provide any material  supporting it is not safe enough or there is some new knowledge saying that, FATE is open to fix it and making progress through the process. 

Thank you for participating in the construction of FATE.

**Comment by vincehong** [comment]
First of all , it's easy to know it's a categorical feature: if X_1 + X_2 + X_3 = total_sum, X is a categorical feature. If total_sum is big (e.g. 100,000+), there's little chance of false positives using this method.

Second, if the security comes from "B not knowing the feature meanings", why doesn't A just simply wipe the feature headers and send the data to B?  After all, B does not know what kind of features A have, and we also cannot provide any material supporting "sending raw data without feature name is not safe enough". 

And we do have a safe way which only outputs the WOE without leaking the number of samples in the bin: it's just a secure inner product and secure division using MPC (which is already included in  https://github.com/FederatedAI/FATE/tree/master/federatedml/secureprotol/spdz).  

FATE put GDPR at its first page, and includes fancy stuff such as homomorphic encryption, so we would naturally think that it was considering security and privacy in a serious way. Please don't discourage us. We do know it's not easy to maintain such a big open-source project, but we should show better respect to security , privacy , and cryptography.

Thanks.

**Comment by tanmc123** [comment]
> First of all , it's easy to know it's a categorical feature: if X_1 + X_2 + X_3 = total_sum, X is a categorical feature. If total_sum is big (e.g. 100,000+), there's little chance of false positives using this method.
> 
> Second, if the security comes from "B not knowing the feature meanings", why doesn't A just simply wipe the feature headers and send the data to B? After all, B does not know what kind of features A have, and we also cannot provide any material supporting "sending raw data without feature name is not safe enough".
> 
> And we do have a safe way which only outputs the WOE without leaking the number of samples in the bin: it's just a secure inner product and secure division using MPC (which is already included in https://github.com/FederatedAI/FATE/tree/master/federatedml/secureprotol/spdz).
> 
> FATE put GDPR at its first page, and includes fancy stuff such as homomorphic encryption, so we would naturally think that it was considering security and privacy in a serious way. Please don't discourage us. We do know it's not easy to maintain such a big open-source project, but we should show better respect to security , privacy , and cryptography.
> 
> Thanks.

At your first point, even if it is not a categorical feature, it still satisfy  X_1 + X_2 + X_3 = total_sum. I cannot get why this could be a proof of a feature being categorical. 

Well, as for the second point, the number in each bin is totally different with raw data. We are just saying, without the meaning of features, only having the number in each bin is safe. Please do not steal the concept. 

As for the MPC way of calculating WOE, that may be a good suggestion, we will try to think about it more detailly. 

FATE do put GDPR at its first page and that's why FATE is an open-source project. FATE open to discuss with our users and to make progress in every possible way. Thanks for you suggestion.
