### ISSUE TITLE
Is it possible to set different weights for imbalanced data samples in the training stage?

### ISSUE THREAD

**Issue by qzhua** [FederatedAI/FATE#1452]
A problem we encountered in homo FL is that when we split a balanced training data set into two parties with high imbalance pos/neg distribution, the classification performance of the obtained model would deteriorate.

We noticed there is a **party_weight** param that can be used to balance the gradient came from different parties, but this would not solve our problem. 
**Our question is that:**
1) If the total number of pos/neg samples can be known in advance in some way, can we set the weights for pos/neg examples manually in the JSON configure files? 
2) If it is possible to let the FL host and guest server negotiate and determine and set those weights accordingly?
3) Can both homo and hetero methods support such a scheme?

**Comment by tanmc123** [comment]
@qzhua Thanks for your suggestion. 

1. This is one of our plan in the future versions. We also plan to make a component to set weights automatically based on the label ratio. 
2. That's part of the first question. We might need to make a better design so that this process is convenient and safe. 
3. Yes, we will try to achieve that. 

Thanks and hope that is useful for you.
