### ISSUE TITLE
关于1.6.0版本CNN&RNN支持

### ISSUE THREAD

**Issue by Yuchen-Li** [FederatedAI/FATE#2786]
Hi guys,

请问有人知道如何在1.6.0集群版本上使用CNN, RNN嘛？貌似没有找到相应的用例以及文档。

Best regards,
Y.Li

**Comment by Yuchen-Li** [comment]
之前在`1.4.0`版本尝试过`CNN`, 速度比较慢, 听说FATE更新了想看看新的版本怎么使用CNN RNN的。

**Comment by nvmoyar** [comment]
Hi! 
I'm also interested in response to this since I'm considering applying FATE to create a federated network for training with images, and there is no too much information about is such a thing is possible or not. Can anyone provide documentation of a use case for regular image classification with CNN's? Thanks a mil.

**Comment by MY-Lucy** [comment]
请问你现在找到关于CNN和RNN的文档或者指导书了吗？
