### ISSUE TITLE
2个bug

### ISSUE THREAD

**Issue by huajinghua** [FederatedAI/FATE#3318]
**Describe the bug**
1. homo_feature_binning 中数据未进行转换
2. 手动指定category字段时，bucket分箱统计结果顺序问题
提交PR :https://github.com/FederatedAI/FATE/pull/3317

**Comment by mgqa34** [comment]
Copy the reply from #3317 
Q1: we have already fixed in develop-1.7 before sep.26, https://github.com/FederatedAI/FATE/blob/develop-1.7/python/federatedml/feature/homo_feature_binning/homo_binning_cpn.py#L56
Q2: In our design, the order of col_index is not importance, the returning result will always start from smaller column to bigger one.

If there are no more reply, this issue and the corresponding pr will be closed soon
