### ISSUE TITLE
请问纵向逻辑回归残差保护解决了吗？

### ISSUE THREAD

**Issue by huajinghua** [FederatedAI/FATE#3691]
据了解，纵向LR可能会存在标签泄漏问题，请问这个是否可以解决？
![image](https://user-images.githubusercontent.com/13927738/152639722-bfa7b4d5-4607-41d4-967b-57746f535b67.png)
目前来看，DP-HE-Hybird 的方案能很快解决该问题

**Comment by dylan-fan** [comment]
Hetero-LR(with Arbiter role) implemented in FATE is not same with your description. But the problem above(when rank(xb) =|B|) also existed in Hetero-LR(with Arbiter role). It will fixed in next version. Please stay tuned. 
Until a new version is released, you can use hetero-sshe-lr algorithm instead.

**Comment by gxcuit** [comment]
> 据了解，纵向LR可能会存在标签泄漏问题，请问这个是否可以解决？ ![image](https://user-images.githubusercontent.com/13927738/152639722-bfa7b4d5-4607-41d4-967b-57746f535b67.png) 目前来看，DP-HE-Hybird 的方案能很快解决该问题

您好，有这个图片的出处吗? Thanks!

**Comment by huajinghua** [comment]
Paper here: https://arxiv.org/pdf/2102.08504.pdf
