### ISSUE TITLE
Roles: Guest, Host, Arbiter

### ISSUE THREAD

**Issue by henrydrp10** [FederatedAI/FATE#4190]
Hello,

I don't really know the meaning of each role, and haven't been able to find it online. I am currently trying to perform horizontal Federated Learning on a Gradient Boosting Decision Tree - HomoSecureBoost. From my understanding, there is a server, who aggregates the local results of the workers, who train subsets of the dataset locally. What do the roles (guest, host and arbiter) actually represent? Why is the RMSE value different between the hosts and the guest at evaluation? Any help is appreciated as soon as possible, thank you.

**Comment by talkingwallace** [comment]
Hi,
1. In the setting of FATE, guest and hosts compute split points locally and the arbiter aggregates data to find best split points. Please refer to Homo-Secureboost documentation. See: https://github.com/FederatedAI/FATE/blob/master/doc/federatedml_component/ensemble.md
2.  This is because guest and host hold different datasets.
3.
