### ISSUE TITLE
Accuracy plot of hetero binary classification

### ISSUE THREAD

**Issue by almrx** [FederatedAI/FATE#4420]
I have been experminting on fate for quite some time. I have some questions about the evaluation module behavior on the binary classification of the hetero_nn model which is one of the examples in fate. The evaluation module plots out the accuracy graph on the fateboard. I expected the accuracy plot to have the y-axis as accuracy and the x-axis as rounds. However, fate generates the accuracy graph differently. I see the y-axis is accuracy but the x-axis is cuts which is the scaled list of matrix_score. The matrix_score is generated based on the last round of predicted labels and the true labels. 

I have two questions,
1. How can I produce the accuracy graph where the x-axis is the number of rounds? 
2. Could you please reason what the current accuracy graph (which has the x-axis as cuts) represents for the training and prediction phases? Currently, the same graph is plotted for both training and prediction. 

![image](https://user-images.githubusercontent.com/39462351/200023849-948ee297-d676-4930-8ec0-1b33f1a70d09.png)

**Comment by talkingwallace** [comment]
Hi, greeting
1. Currently FATE does not support display acc curves whose x-axis is the number of rounds. 
2. It seems that your fateboard didn't have a validate set display. This may happens when the sample ids of the validate set 
   overlaps with training set's ids.
![image](https://user-images.githubusercontent.com/10768970/200099666-45c6fd35-2792-43a9-b9cc-5f4815d757b1.png)
