### ISSUE TITLE
The PSI implemented is not fully secure.

### ISSUE THREAD

**Issue by vincehong** [FederatedAI/FATE#509]
**Describe the bug**
The PSI implemented in FATE/federatedml/statistic/intersect/ is not fully secure.

**To Reproduce**
Suppose A and B are doing PSI.

Step 1: B  generates  all  possible  primes  p_1,p_2,...p_n  <  2^32    (about  200,000,000  x)
Step 2: B  sends  r_i^e * p_i,  together  with  other  "legal" data to  A    (The  extra n pieces of data is  reasonable  in  a  billions  vs  billions  PSI)
Step 3: Innocent  A  cast  (r_i^e * p_i)^d  (which is  r_i * p_i^d) on  all  of  the  data r_i^e * p_i sent  by  B.
Step 4: B  receives  r_i * p_i^d and computes p_i^d

Now  suppose  B  want  to  guess  whether  a  data  D  is  in  A's  data  set.    

Step  1:  Compute  SHA256(D),  obtain  256  bit  integer  s.
Step  2:  Factor  s.  There's  an  unnegligible  chance  that  s  could  be  factored  into  short  (<2^32)  primes,  which  is  already  pre-computed.  [http://www.crypto-uni.lu/jscoron/publications/padding.pdf]
//the  chance  is  above 2^-23  ≈  1  out  of  8,000,000  ，  which  means  several  hundreds  of  possible leakages  in  the  case  of  mobile  phone  number  /  device  id.
Step  3.  Compute  s^d  from  p_i^d,  compute  h  =  SHA256(s^d)
Step  4.  Check  if  h  is  in  the  data  set  from  A

**Additional context**

Suggested countermeasure 1: Use a PSI algorithm that is provable secure.
Suggested countermeasure 2 (If 1 cannot be done) : Change SHA256 to SHA512 to reduce the leakage.

**Comment by zazd** [comment]
Thanks for your feedback， we will checkout this

**Comment by vincehong** [comment]
@dylan-fan Not sure why this is closed. Talked with Tianjian Chen today, and it should be re-opened.

**Comment by dylan-fan** [comment]
> @dylan-fan Not sure why this is closed. Talked with Tianjian Chen today, and it should be re-opened.

Thank you for your advice.

**Comment by dylan-fan** [comment]
If convenient, could you please provide your email or wechat? We will continue our communication

**Comment by YongGuCheng** [comment]
@vincehong  @dylan-fan @Tianjian 
A few points from my understanding:
1. The attack example given by @vincehong is an adversarial attack, while the blind RSA approach is applicable for semi-honest parties (see the original paper).  Thus, the attack example may not be fair for the blind RSA approach.
2. The attack example given by @vincehong may not work, since Party A can simply shuffle the encrypted-hashed IDs, so that Party B will not know which ones are {p_i^d mod n}s.
3. The first hash in the blind RSA approach shall be a full-domain hash (see the original paper).
4. There is some chance that Party A can detect the attack example given by @vincehong.  So, Party B better not carry out such an attack.

Case closed.
