### ISSUE TITLE
Fix bug: when run quick_run.py raise ImportError: cannot import name 'itemgetter'

### ISSUE THREAD

**Issue by shikanon** [FederatedAI/FATE#518]
**Describe the bug**
When run the script of quick_run.py, it will rasie ImportError like this:
```
stdout:Traceback (most recent call last):
  File "/home/wy/FATE/examples/federatedml-1.0-examples/../../fate_flow/fate_flow_client.py", line 17, in <module>
    import argparse
  File "/home/wy/.pyenv/versions/3.6.0/lib/python3.6/argparse.py", line 86, in <module>
    import collections as _collections
  File "/home/wy/.pyenv/versions/3.6.0/lib/python3.6/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
ImportError: cannot import name 'itemgetter'
```

**To Reproduce**
1. Go to 'python quick_run.py'
2. See error

**Comment by weiwee** [comment]
@shikanon this error is relative to python's import system behavior.  The module `collections` fails to  import standards modules `operator`  because there is a same file named `operator` under the same directory with fate_flow_client.  But this won't be a problem in python 3.6 unless you manually add fate_flow/  to `PATHTHONPATH` environment.
