### ISSUE TITLE
运行给的train_ly.yaml，失败后显示 No found task output.，请问要怎么解决

### ISSUE THREAD

**Issue by Defu-csh** [FederatedAI/FATE#5548]
![image](https://github.com/FederatedAI/FATE/assets/74239663/b996089c-e919-46f2-b1c7-72e5f0074186)

**Comment by mgqa34** [comment]
fate_flow/logs/$job_id下面有具体错误吗？

**Comment by Defu-csh** [comment]
[INFO.log](https://github.com/FederatedAI/FATE/files/14634299/INFO.log)
[fate_flow_schedule.log](https://github.com/FederatedAI/FATE/files/14634306/fate_flow_schedule.log)
这是下面的日志，没太看出来具体错误是什么

**Comment by mgqa34** [comment]
> [INFO.log](https://github.com/FederatedAI/FATE/files/14634299/INFO.log) [fate_flow_schedule.log](https://github.com/FederatedAI/FATE/files/14634306/fate_flow_schedule.log) 这是下面的日志，没太看出来具体错误是什么

看std日志，fate_flow/logs/${job_id}/${错误方的角色}/${错误方的party_id}/binning_0/stdout/，下面有几个文件，可以看看是否有错误

**Comment by Defu-csh** [comment]
认真看了一下，好像是kit = ctx.cipher.phe.setup()，然后在keygen的时候就卡住，然后失败，请问运行这个rust写的fate_utils是需要什么环境呢

**Comment by sagewe** [comment]
> 认真看了一下，好像是kit = ctx.cipher.phe.setup()，然后在keygen的时候就卡住，然后失败，请问运行这个rust写的fate_utils是需要什么环境呢

有可能预编译包不兼容，尝试手动编译试试

1. 配置rust环境 https://www.rust-lang.org/zh-CN/tools/install
2. 安装maturin https://github.com/PyO3/maturin
3. 激活虚拟环境后进入rust/fate_utils 目录执行 maturin build --release 即可，可以在dist目录下找到当前环境可用的预编译whl包，拷贝到相同的环境安装即可使用

另外方便的话提供系统环境信息给我们，我们会尝试发布对应的预编译包到PyPI

**Comment by RayWang99** [comment]
> > 认真看了一下，好像是kit = ctx.cipher.phe.setup()，然后在keygen的时候就卡住，然后失败，请问运行这个rust写的fate_utils是需要什么环境呢
> 
> 有可能预编译包不兼容，尝试手动编译试试
> 
> 1. 配置rust环境 https://www.rust-lang.org/zh-CN/tools/install
> 2. 安装maturin https://github.com/PyO3/maturin
> 3. 激活虚拟环境后进入rust/fate_utils 目录执行 maturin build --release 即可，可以在target/wheels目录下找到当前环境可用的预编译whl包，拷贝到相同的环境安装即可使用
> 
> 另外方便的话提供系统环境信息给我们，我们会尝试发布对应的预编译包到PyPI

/fate_utils/target是空文件夹，下面什么都没有，以上述方式尝试编译2.1版develope里的toml，报错如下：
......
......
Compiling fixedpoint v0.1.0 (/home/app/rust_temp/fate_utils/crates/fixedpoint)
Compiling fate_utils v0.1.0 (/home/app/rust_temp/fate_utils/crates/fate_utils)
error: multiple input filenames provided (first two filenames are crates/fate_utils/src/lib.rs and —release)

error: could not compile fate_utils (lib) due to 1 previous error
💥 maturin failed
Caused by: Failed to build a native library through cargo
Caused by: Cargo build finished with "exit status: 101": env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.8-64bit" PYO3_PYTHON="/home/app/projects/fate/common/python/venv/bin/python" PYTHON_SYS_EXECUTABLE="/home/app/projects/fate/common/python/venv/bin/python" "cargo" "rustc" "--message-format" "json-render-diagnostics" "--manifest-path" "/home/app/rust_temp/fate_utils/crates/fate_utils/Cargo.toml" "--lib" "--crate-type" "cdylib" "--" "\xe2\x80\x94release" "-C" "link-arg=-s"

**Comment by RayWang99** [comment]
> > 认真看了一下，好像是kit = ctx.cipher.phe.setup()，然后在keygen的时候就卡住，然后失败，请问运行这个rust写的fate_utils是需要什么环境呢
> 
> 有可能预编译包不兼容，尝试手动编译试试
> 
> 1. 配置rust环境 https://www.rust-lang.org/zh-CN/tools/install
> 2. 安装maturin https://github.com/PyO3/maturin
> 3. 激活虚拟环境后进入rust/fate_utils 目录执行 maturin build --release 即可，可以在target/wheels目录下找到当前环境可用的预编译whl包，拷贝到相同的环境安装即可使用
> 
> 另外方便的话提供系统环境信息给我们，我们会尝试发布对应的预编译包到PyPI

去掉—release
maturin build 可以执行，产生whl文件，fate_utils-0.1.0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
不过用pip 强制重装之后，原有的报错没有发生改变

**Comment by Defu-csh** [comment]
任务执行成功了，谢谢大佬！
