### ISSUE TITLE
task failed, but task_executor.py on port 9380 still be alive

### ISSUE THREAD

**Issue by bigcash** [FederatedAI/FATE#683]
**Describe the bug**
    当我的任务失败时，发现9380端口上的服务还存在，并没有随着任务失败被关闭。
    我第一次使用hetero_lr/rmsprop/batch_size=2000训练数据，auc0.76是成功的，所以进行第二次尝试，将optimizer改为sgd，但是这次运行到iter=27时出错了，查看arbiter的日志，发现错误是"ask_executor.py[line:125] - ERROR: Overflow detected in decode number"。这时guest和host上的任务都显示失败了，虽然没有错误原因，但确实都显示task failed。但我查看系统进程，发现guest上的9380的服务并没有被杀掉，“python3 /data/projects/fate/python/fate_flow/driver/task_executor.py -j 2019101719574797565013 -n hetero_lr_0 -t 2019101719574797565013_hetero_lr_0 -r guest -p 10000 -c /data/projects/fate/python/jobs/2019101719574797565013/guest/10000/hetero_lr_0/task_config.json --job_server 127.0.0.1:9380”，如果这个进程还在，将会影响下一个任务的运行。所以我觉得这可能是个bug，这里我只能自己手动kill掉这个进程了。
    （顺便说一下，我任务中报的这个错误，发现是因为loss值太大了，已经e134次幂了，这可能因为我的数据引起的，改了sgd后，损失计算的问题，需要我进一步分析了。）
    不知这是否是一个bug，多谢开源！

**Comment by tanmc123** [comment]
@bigcash 
Thanks for your question and I apology that the question need to be answered in English. 

As you mentioned, there indeed exists a bug in fate-flow for killing failure task. in FATE1.0. When running a federated task, if the task in one party, let say Host party, failed, the task in Guest party will not be killed simultaneously even though it is killed in host. This bug will be fix in FATE1.1. Sorry for the misinformation. 

As for the exposure of loss, this might be caused by the un-normalized input data. Since we use Talor expansion to fit original loss function in encryption mode, it is quite sensitive for the scale of input data. 

Hope that is useful for you.

**Comment by bigcash** [comment]
@tanmc123 thank you, hope for new release FATE1.1.
