### ISSUE TITLE
是否支持多方计算和单方多机器加速扩展计算

### ISSUE THREAD

**Issue by bihaiyuanqing** [FederatedAI/FATE#779]
1、请问FATE是否支持多方计算？比如a、b、c、d四方计算？
2、是否支持两方建模计算时，各方通过增加机器数来均分大数据量，实现通过机器数来增加训练速度？
3、请问现在支持的最大训练数据量是多少维度和多少行？因为我在用mnist数据集实验过程中发现，训练特别慢？
4、FATE的性能指标的现状是什么？比如训练速度，对输入的兼容性，在不同稀疏度下是否有训练优化，是否归一化对结果有影响。
请您回复或者邮件通知我574448638@qq.com
thanks~

**Comment by codergan** [comment]
Same here, if possible. My email: ethan.gan.xin@gmail.com

**Comment by mgqa34** [comment]
Q1: More algorithm Support Multi-host Training and Prediction.  In FATE-1.1，Intersection\HeteroLR\HeteroSecureBoost\HeteroLinearRegression\HomoLR\HomoDNN supports multi-host federation. In later version of FATE, we will support multi-party feature engineering too.
Q2: Yes, fate use eggroll\spark api, eggroll\spark support multi-machine deploy.
Q3:  Actually, we doesn't limit the row of data，but in some algorithm. the single object should be smaller than 32M due to value limitation of eggroll. (e.g. encrypted weights in homo-lr, feature histogram of secureboost)  We use homomorphic encryption like "paillier" protocol, which will slow down the training process. 
Q4: Many Algorithm in FATE supports only dense-numpy vector, only HeteroSecureBoost and HeteroFeatureBinning supports sparse data format.  In our testing, use homomorphic encryption protocol will be hundreds times slower than sklearn, we will speed up homomorphic encryption by using heterogeneous computing later.

**Comment by bihaiyuanqing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到您的邮件，并会尽快给您回复。
