### ISSUE TITLE
logic in quick_run.py may not right.

### ISSUE THREAD

**Issue by TerrenceKao** [FederatedAI/FATE#792]
In quick_run.py:if \__name\__ == '\__main\__'(),  the if/else statement below would print ValueError if the host only does `upload_data()'. However this is actually not an error which using a host to initiate a prediction. For example, if a user wants to do LR, he/she should use quick_run to upload host's data first. If doing so, the ValueError would be raised.

    try:
        args = parser.parse_args()
        upload_data()
        if TASK == 'train' and args.role == GUEST:
            submit_job()
        else:
            if args.role == HOST:
                raise ValueError("Predict task can be initialed by guest only")
            predict_task()

**Comment by tanmc123** [comment]
@TerrenceKao 

Thanks for your question. Quick_run is designed for user experience FATE quickly. What we designed in quick_run contains uploading data only in host (For training purpose), uploading and starting training in guest and starting predict task in guest. In predict task, we use the previews trained model as well as the trained data. That's why we have the logic you mentioned. 

However, it is really a good suggestion to develop scrips for easily using FATE which is not purpose on experiencement only. And we do working on it. Please look forward to our future releases. 

Thanks again for your question and hope that is useful for you.

**Comment by TerrenceKao** [comment]
> @TerrenceKao
> 
> Thanks for your question. Quick_run is designed for user experience FATE quickly. What we designed in quick_run contains uploading data only in host (For training purpose), uploading and starting training in guest and starting predict task in guest. In predict task, we use the previews trained model as well as the trained data. That's why we have the logic you mentioned.
> 
> However, it is really a good suggestion to develop scrips for easily using FATE which is not purpose on experiencement only. And we do working on it. Please look forward to our future releases.
> 
> Thanks again for your question and hope that is useful for you.

got it. thanks!
