### ISSUE TITLE
homo_breast_* example evaluation

### ISSUE THREAD

**Issue by cometta** [FederatedAI/FATE#824]
I able to run the homo_breast_* example with config file :test_multi_host_job_conf.json,  By default "evaluation" is run on the guest. 

When i change the config file evaluation_0 for "Host" to true in test_multi_host_job_conf.json, the job will fail to run. Can help to explain on this?

Also, where can we see the output of the model after ran the job successfully?

**Comment by tanmc123** [comment]
@cometta 

In the predict task, host send wx to arbiter and arbiter make the judgement of which class a sample belongs to. Therefore, a host has no way to get the predict score of samples which means the host cannot calculate the evaluation indicators such as auc etc. That's why we make evaluation module Inoperable. 

As for the second question, if you have deploy a fate-board, the model results will be avaiable in the visual interface. However, that is not your case, we recommend you obtain the model info by fate-flow cli whose documentation is located here:  https://github.com/FederatedAI/FATE/blob/master/fate_flow/doc/fate_flow_cli.md#component_output_model

Hope that is useful for you.
